version: "3.9"

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/usr/share/redis/data

volumes:
  redis-data:
    driver: local
